# Generated by Django 3.2.8 on 2021-10-28 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('sex', models.CharField(max_length=100, verbose_name='')),
                ('id_number', models.CharField(max_length=255, unique=True, verbose_name='ID Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('logo', models.ImageField(upload_to=None, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=512)),
                ('result', models.CharField(max_length=255)),
                ('desired_result', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=None, verbose_name='File')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.client', verbose_name='Client')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.lab', verbose_name='')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.tester', verbose_name='Performed By')),
            ],
        ),
    ]
