# Generated by Django 3.2.8 on 2021-11-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(max_length=100, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(null=True, upload_to=None, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.lab', verbose_name='Lab'),
        ),
    ]
