# Generated by Django 3.2.8 on 2021-11-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='logo',
        ),
        migrations.AddField(
            model_name='lab',
            name='footer',
            field=models.ImageField(height_field='footers', null=True, upload_to=None, verbose_name='Footer'),
        ),
        migrations.AddField(
            model_name='lab',
            name='header',
            field=models.ImageField(height_field='headers', null=True, upload_to=None, verbose_name='Header'),
        ),
    ]
