# Generated by Django 3.2.8 on 2021-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20211102_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tester',
            name='signature',
            field=models.ImageField(null=True, upload_to='signatures', verbose_name='Signature'),
        ),
    ]
