# Generated by Django 3.2.8 on 2021-11-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_tester_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Number'),
        ),
    ]
