# Generated by Django 3.2.8 on 2021-11-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_client_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='stamp',
            field=models.ImageField(null=True, upload_to='stamps', verbose_name='Stamp'),
        ),
    ]
