# Generated by Django 3.2.8 on 2021-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_lab_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='unit_date',
        ),
        migrations.AlterField(
            model_name='lab',
            name='footer',
            field=models.ImageField(blank=True, null=True, upload_to='footers', verbose_name='Footer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='branch_no',
            field=models.CharField(blank=True, default='00', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='desired_result',
            field=models.CharField(default='NOT DETECTED', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(default='<p>INTERPRETATION:</p><p>NOT DETECTED - NEGATIVE</p><p>DETECTED - POSITIVE</p><p>A negative result does not rule out infection with SARS-CoV-2 and should not be used as a sole basis, for diagnosis. <br>Symptomatic patients, if negative, SHOULD be RETESTED (2-3 days).<br>AMPLIFICATIONS Require a REPEAT swap (24-48hrs). <br>This test was performed utilising E-Gene RT-PCR on a Rotor Gene Q Instrument.<br>Methodology: Reverse Transcription Polymerase Chain Reaction (RT-PCR).<br>Sample Type: Nasopharyngeal Swab</p><p>N.B APPROVED BY THE MINISTRY OF HEALTH (TRINIDAD AND TOBAGO).</p><p></p>'),
        ),
        migrations.AlterField(
            model_name='report',
            name='doctor',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.CharField(default='NOT DETECTED', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='test_request',
            field=models.CharField(default='COVID PCR', max_length=512),
        ),
    ]
