# Generated by Django 3.2.8 on 2021-11-14 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20211112_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(default='<p>INTERPRETATION:</p><p>NOT DETECTED - NEGATIVE</p><p>DETECTED - POSITIVE</p><p>A negative result does not rule out infection with SARS-CoV-2 and should not be used as a sole basis, for diagnosis. <br>Symptomatic patients, if negative, SHOULD be RETESTED (2-3 days).<br>AMPLIFICATIONS Require a REPEAT swab (24-48hrs). <br>This test was performed utilising E-Gene RT-PCR on a Rotor Gene Q Instrument.<br>Methodology: Reverse Transcription Polymerase Chain Reaction (RT-PCR).<br>Sample Type: Nasopharyngeal Swab</p><p>N.B APPROVED BY THE MINISTRY OF HEALTH (TRINIDAD AND TOBAGO).</p><p></p>'),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.lab', verbose_name='Lab'),
        ),
        migrations.AlterField(
            model_name='report',
            name='order_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='performed_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.tester', verbose_name='Performed By'),
        ),
    ]
