# Generated by Django 3.2.8 on 2021-11-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20211114_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='insurance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='order_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
